services:
  dev:
    build:
      context: .
      target: dev
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

  test:
    profiles: ["test"]
    build:
      context: .
      target: dev
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules

  cli:
    profiles: ["cli"]
    build:
      context: .
      target: cli
    volumes:
      - .:/programs

  preview:
    profiles: ["preview"]
    build:
      context: .
      target: prod
    ports:
      - "8080:80"
